# 1)a.To check whether a number is prime or not

In [ ]:
number = int(input("Enter any number: "))# input number

# prime number is always greater than 1
def isprime(a):
    if number > 1:
        for i in range(2, number):
            if (number % i) == 0: # checking prime number
                print(number, "is not a prime number")
                break
        else:
            print(number, "is a prime number")

# if the entered number is less than or equal to 1
# then it is not prime number
    else:
        print(number, "is not a prime number")
print(isprime(number)) # print output       

# b. To find the longest word in a sentence given as input by the user

In [7]:
# Longest word

# Reading sentence from user

sentence = input("Enter sentence: ")

# Finding longest word
longest = max(sentence.split(), key=len)

# Displaying longest word
print("Longest word is: ", longest)
print("And its length is: ", len(longest))

Enter sentence: iuhfue urfug fuygwuygd uhadjhbiuwehd uhhdoi iuuhua
Longest word is:  uhadjhbiuwehd
And its length is:  13


# c. To find how many times a given user-inputted substring is repeated in another user inputted string

In [8]:
# enter a string
g = "rferhfiuhxiuhfn8wehefy"
h = "f"

def count_substring(a,b):#checking length of string
    len1 = len(g)
    len2 = len(h)
    j =0
    counter = 0
    while(j < len1): #checking the repetition of sub string
        if(g[j] == h[0]):
            if(g[j:j+len2] == h):
                counter += 1
        j += 1

    return counter
print(count_substring(g, h))

4


# 2.

# Create the following class with the given attributes and methods;
### Attributes: Std name, No of enrolled students, Overall GPA
### Methods: getStd, getEnrolled, getOGPA
### Students class with Standard as its super class  - 
### Attributes: Name,Roll No., Standard, Math marks, English Marks, Science Marks, Social Marks
### Methods: getName, getRollNo, getStd, getGPA

In [45]:
#creating student class
class Student:
    marks = []
    def getName(self, rn, name,standard, m1, m2, m3,m4):  #initializing information
        Student.rn = rn
        Student.name = name
        Student.standard= standard
        Student.marks.append(m1)
        Student.marks.append(m2)
        Student.marks.append(m3)
        Student.marks.append(m4)
        
    def getEnrllod(self): # create function to contain information
        print ("Roll Number is: ", Student.rn)
        print ("Name is: ", Student.name)
        print ("Standardof the student  is: ", Student.standard)
        print ("Marks are: ", Student.marks)
        print ("Average  Mark is: ", self.average())
        print (f"Percentage is: ,{ self.percentage()}%")
        print ("CGPA is: ", self.getOgpa())     
        
    def average(self): # calculating average value 
        return (Student.marks[0] + Student.marks[1] +Student.marks[2] +Student.marks[3])/4
    
    def percentage(self):# calculating percentage
        global df
        df=(Student.marks[0] + Student.marks[1] +Student.marks[2] +Student.marks[3] )/400*100
        return df
    
    def getOgpa(self): # calculating CGPA
        cgpa = (df/9.5) 
        return cgpa
r = int (input("Enter the roll number: ")) # collecting student information
name = input("Enter the student name: ")
standard= input("Enter student standard: ")
m1 = int (input("Enter the math mark: "))
m2 = int (input("Enter the english mark: "))
m3 = int (input("Enter the scince mark: "))
m4 = int (input("Enter the social mark: "))

s1 = Student() # execute function 
s1.getName(r, name,standard, m1, m2, m3, m4)
s1.getEnrllod()
s1.average()
s1.percentage()
s1.getOgpa()

Enter the roll number: 87
Enter the student name: gvh
Enter student standard: 87
Enter the math mark: 67
Enter the english mark: 98
Enter the scince mark: 78
Enter the social mark: 78
Roll Number is:  87
Name is:  gvh
Standardof the student  is:  87
Marks are:  [67, 98, 78, 78]
Average  Mark is:  80.25
Percentage is: ,80.25%
CGPA is:  8.447368421052632


8.447368421052632

# 3) a. Create a function to find the indices of a parameter passed to the function in a user inputted array

In [52]:
# inputed array
vowels = ['a', 'e', 'i', 'o', 'u']

# finding indices of a special charecter
index = vowels.index('e')

print('The index of p:', index)

The index of p: 1


# b. Create a random vector of size 30 and find the mean value

In [48]:
import numpy as np
Z = np.random.random(30)
m = Z.mean()
print (m)

0.4782017768795423


# c. Create a 2d array with 1 on its edges and 0 in all other indices

In [49]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# d. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [50]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
